heypanel:
  feature:
    flags:
      - name: v6.7.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.8.0.0
        default: false
        major: true
        toggleable: false
      - name: DISABLE_VUE_COMPAT
        default: true
        major: true
        toggleable: false